### ISSUE TITLE
list of possible initiator types from the resource timing API?

### ISSUE THREAD

**Issue by ThierryMajutec** [w3c/navigation-timing#145] opened 2021-04-20 08:39 UTC
Is there any available list of initiator types supported by the resource timing API ?
For example, I see things like "internal" as initiator type from this API in measures I perform, but do not find any available literature.

**Comment by npm1** [comment] 2021-04-20 17:08
I think there was one before... @noamr could we add a note explaining this a bit? It seems to come from `mark resource timing` but someone reading the spec cannot know where that is being invoked.

**Comment by noamr** [comment] 2021-09-22 06:24
Marking as duplicate of https://github.com/w3c/resource-timing/issues/276. Please also follow https://github.com/whatwg/html/issues/6542 if interested in the specifics.

**Closed by noamr** 2021-09-22 06:24 UTC
