### ISSUE TITLE
Computing nextHopProtocol

### ISSUE THREAD

**Issue by spanicker** [w3c/navigation-timing#71] opened 2017-06-14 19:40 UTC
The purpose of this issue is to document the currently agreed upon proposal for computing nextHopProtocol and track any changes:
1. When alpn negotiated protocol is available, then nextHopProtocol takes its value.
2. nextHopProtocol will fallback to connectionInfo when alpn is unknown
3.  nextHopProtocol will fallback to “http/1.1” when both alpn and connectionInfo are unknown
4.  If alpn (after fallback) is quic, then convert it to “hq”
For eg. in chromium “quic/1+spdy/3”, converted to “hq“. The reason for this is:
- IETF has not made a final determination on QUIC yet, but current proposal is “hq”
- SPDY is deprecated, therefore we’d like to not surface that.

**Comment by igrigorik** [comment] 2017-06-14 20:18
Note that definition lives in ResourceTiming: https://w3c.github.io/resource-timing/#dom-performanceresourcetiming-nexthopprotocol

> On getting, the attribute nextHopProtocol returns the network protocol used to fetch the resource, as identified by the ALPN Protocol ID [RFC7301]; resources retrieved from relevant application caches or local resources, return an empty string. When a proxy is configured, if a tunnel connection is established then this attribute must return the ALPN Protocol ID of the tunneled protocol, otherwise it must return the ALPN Protocol ID of the first hop to the proxy. In order to have precisely one way to represent any ALPN protocol ID, the following additional constraints apply: octets in the ALPN protocol must not be percent-encoded if they are valid token characters except "%", and when using percent-encoding, uppercase hex digits must be used.
>
> Note that the nextHopProtocol attribute is intended to identify the network protocol in use for the fetch regardless of how it was actually negotiated; that is, even if ALPN is not used to negotiate the network protocol, this attribute still uses the ALPN Protocol ID's to indicate the protocol in use.

---

> nextHopProtocol will fallback to connectionInfo when alpn is unknown

connectionInfo is a blink specific construct? Note that that we're not requiring an ALPN negotiation, we're simply stating that the value of nextHopProtocol should be an ALPN ID, which can be derived from the TLS handshake, or through some other means -- e.g. in absence of TLS handshake, based on version string of the negotiated connection, etc.

> nextHopProtocol will fallback to “http/1.1” when both alpn and connectionInfo are unknown

Per processing algorithm, we set nextHopProtocol to empty string at the start, and then update it later based on connection type. We don't have any logic to assume "http/1.1".. and I'm not sure we should? In such cases we should keep it as empty string. 

> If alpn (after fallback) is quic, then convert it to “hq”

Defined in https://tools.ietf.org/html/draft-ietf-quic-http-04#section-9.1 - lgtm.

--- 

What are the resolutions next steps here? Is simply to confirm the implementation? I don't see any spec related issues that we need to address?

**Comment by spanicker** [comment] 2017-06-14 21:23
Thanks for the pointer and clarification that we shouldn't use http/1.1 as fallback -- this was based on FF's implementation that we decided to emulate in a previous thread.

Main resolution needed is to document the "hq" fallback, should this be mentioned in RT?

**Comment by igrigorik** [comment] 2017-06-14 21:41
FWIW, I don't think we need to explicitly document "hq". QUIC RFC registers the token with ALPN registry, we surface registered ALPN tokens.

**Comment by yoavweiss** [comment] 2017-06-16 14:58
I agree "hq" doesn't require explicit documentation beyond the QUIC RFC. OTOH, what we do with unknown ALPN values probably should be documented in RT. I wonder if there are cases where this happens that are not covered by: 
> resources retrieved from relevant application caches or local resources, return an empty string.

**Comment by yoavweiss** [comment] 2017-06-16 15:14
On second thought, I think converging everything QUIC to "hq" might be a bit premature.
Right now, Google's QUIC and IETF's QUIC (which only the latter registers the "hq" ALPN) are 2 distinct protocols, and while there are intentions to converge, right now they may have different performance capabilities.

Furthermore, Google's QUIC is being rapidly iterated on, which means that certain versions of the protocol may suffer from regressions. Hiding the protocol flavor and the version info from the `nextHopProtocol` metric would mean that we would have a hard time finding such regressions and performance differences between the protocol versions and flavors using RUM data.

/cc @mnot @janaiyengar

**Comment by yoavweiss** [comment] 2017-06-16 15:19
Protocol versions is something we might be able to deduce from browser versions, so it might not be a big deal to hide them, but just as SPDY had a different ALPN name, it might be worth while to expose GQUIC vs. IQUIC here

**Comment by igrigorik** [comment] 2017-06-16 19:04
For context, there was pushback on [blink-dev i2s](https://groups.google.com/a/chromium.org/forum/#!searchin/blink-dev/nexthopprotocol/blink-dev/Hs5-wPpCPZc/7BVwLbfMAAAJ) for exposing internal Blink versions: there is no agreement on how these are minted or what they mean across different implementation, which I think is fair. One option we discussed was not to report QUIC at all and settled on using "hq" as it conforms to the definition -- a valid ALPN ID, etc.

I propose we proceed with current plan: "hq". If you disagree, let's take it to blink-dev.. I don't think that's a discussion for this list.

Closing, as I don't think there is anything spec-actionable here.

**Closed by igrigorik** 2017-06-16 19:04 UTC

**Comment by RyanAtGoogle** [comment] 2018-03-14 17:43
Sorry for the thread necromancy. A recent discussion[1] at the QUIC IETF Working Group revealed that the use of "hq" is reserved for the final version of HTTP over QUIC. Since that specification is a working in progress, "hq" is forbidden from being used.

   Only implementations of the final, published RFC can identify
   themselves as "hq".  Until such an RFC exists, implementations MUST
   NOT identify themselves using this string.

This means that Chrome, which implements a version of QUIC which is not the final version of QUIC (and which is not currently a specific draft version of QUIC) should use a different identifier. The QUIC WG editors had no preference for what identifier Chrome should use, other than not using "hq". The identifier Chrome had been using in the past was of the form:

 http/2+quic/<version number>

I recommend Chrome switch back to using this identifier until Chrome supports the official version of HTTP over QUIC.

[1] https://mailarchive.ietf.org/arch/msg/quic/a51FAmhnl3-DXfkB4DFKkklcIMY

**Comment by igrigorik** [comment] 2018-03-15 21:02
@RyanAtGoogle thanks for flagging this here. Yes, that makes sense. 👍
